services:
  - type: web
    name: storepro-sklad
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
